### ISSUE TITLE
[question] best approach for "bw login" from python

### ISSUE THREAD

**Issue by aptly-io** [bitwarden/cli#351] opened 2021-07-16 06:23 UTC
## Describe the Bug

I use python as a wrapper around the bw client tool like the script lines below to access the vault.
I'm not happy about the not so safe `BW_SESSION` shell variable exposed as an environment variable.
Are there a safer approaches to this?
Like, could I talk through a socket with the `bw` client so that peeking in the communication is less trivial? Or encrypt the session value with a key that only python-script and `bw` know before sharing it through the shell ... ?

Thanks!

```python
session = subprocess.check_output(["bw", "--raw", "login"])
env = dict(os.environ, BW_SESSION=session)

# reading
items = subprocess.check_output(["bw", "--raw", "list", "items"], env=env)

# writing
object = base64.b64encode(bytes(json.dumps(object), "utf-8"))
result_json = check_output(["bw", "create", "item"], env=env, input=object)
```

## Steps To Reproduce

See the small script above.

## Expected Result

Increase security by preventing looking into environment variables

## Environment

- macOS/Ubuntu
- Shell: linux like shells
- Build Version (run `bw --version`): 1.17.1

**Comment by eliykat** [comment] 2021-07-18 21:29
You can pass the session key via an argument instead:

```
bw list items --session "5PBYGU+5yt3RHcCjoeJKx/wByU34vokGRZjXpSH7Ylo8w=="
```

[Source](https://bitwarden.com/help/article/cli/#using-a-session-key)

Maybe your python program could append the `--session` argument to each Bitwarden CLI command it constructs? Not foolproof but much less exposed than a session variable, depending on what threats you're concerned about.

@MGibson1 might have some other ideas here.

That said, we use Github fairly strictly for bugs, defects and other development-related issues. Questions like these are better suited for the [Community forums](https://community.bitwarden.com/) (more active) or the [Gitter developer chat](https://gitter.im/bitwarden/Lobby). I'll close this thread because this is the intended behaviour (even if not suitable for your case).

**Closed by eliykat** 2021-07-18 21:29 UTC

**Comment by aptly-io** [comment] 2021-07-19 05:52
@eliykat Thanks for your answer/suggestion. 

I leave this closed (maybe security enhancements could be considered more than just a feature request?)
I think passing the session as an argument is in the same league as using env. variable:
someone else on the workstation can list all active processes with `ps` (on unix/macOS like systems).
This shows all running processes.
And given the correct command line arguments it shows exactly with which command line (including details on all arguments) the process was started.

**Comment by MGibson1** [comment] 2021-07-19 14:11
Hey @aptly-io, The reason the session toke exists is because the CLI is short-lived. We need a way to unlock a vault without necessarily needing a master password every time.

Have you tried storing the session key in your python script's memory and prepending the `BW_SESSION` variable in your `os.system` call?
```python
import subprocess
import os
my_env = os.environ.copy()
my_env['BW_SESSION'] = 'your session token'
subprocess.run('bw list items --response'.split(), capture_output=True, env=my_env)
```

The environment should be unique to your subprocess and will not show up in `ps` calls.

I'm interested in what the attack vector you're worried about is. Are you concerned with adding a session key to your `rc` files? I personally wouldn't recommend that. The idea is to be a little more transient than that.

**Comment by aptly-io** [comment] 2021-07-20 05:39
@MGibson1 Thank you for your suggestion. Passing `env` to the `subprocess` module is what I currently do as an improvement of the `--session` argument (see the code snippet in my question above).
Regarding the attack vector, although I did not try this myself (I'm on a macOS while writing), these links explain how to access the env. var. list of a running process with basically just a `cat /proc/<PID>/environ` on Linux:
- https://unix.stackexchange.com/questions/29128/how-to-read-environment-variables-of-a-process
- https://serverfault.com/questions/66363/environment-variables-of-a-running-process-on-unix
- https://ma.ttias.be/show-the-environment-variables-of-a-running-process-in-linux/

I could image other OS-es offer similar facilities (e.g. windows has something like the `ProcessExplorer`: https://docs.microsoft.com/en-gb/sysinternals/downloads/process-explorer).

When time permits, I'll try the Bitwarden REST API directly from python. For now wrapping around `bw` is convenient.

PS 
- Compared to doing a simple `ps -ef`, looking into `proc/<PID>/environ` might require extra privileges.
- From security point of view, the cli user could specify an extra argument like `--development-only` to be able to use the less secure `--session` (As an acknowledgement he/she is aware of a less secure access to the vault).

**Comment by MGibson1** [comment] 2021-07-20 14:51
You're right, I was able to pull the session variable out using `ps eww <PID>`. 

My initial stance on this is that it's very similar to our GUI clients in an unlocked state. If you're walking away from your computer, lock it. There might be some added concern due to a potentially easier attack vector for spyware, but if that's a concern, you don't _need_ to use the session variable at all.

It might be interesting to make session optional and if it's not set, prompt for it using inquirer

**Comment by aptly-io** [comment] 2021-07-20 15:37
@MGibson1 Thank you for verifying. You are right on your concerns; while using the UI, the user can protect the contents when some peeks over once shoulder. While using scripting, one cannot stop someone from scripting with nasty intentions. But I understand better the possibilities and its limitations and leave this ticket as it is.
