### ISSUE TITLE
UnhandledPromiseRejectionWarning with bw get attachment

### ISSUE THREAD

**Issue by ggiesen** [bitwarden/cli#310] opened 2021-05-25 14:53 UTC
## Describe the Bug

Receive the following error when attempting to get an attachment in version 1.16.0 installed on CentOS 8:
```
$ bw get attachment Test.txt --itemid b3fc5016-86d8-4296-87f8-ac7901397fa0 --output /tmp/Test.txt
? Master password: [hidden]
(node:2884686) UnhandledPromiseRejectionWarning: Error
    at get_command_GetCommand.<anonymous> (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:27599:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:27338:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2884686) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2884686) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Steps To Reproduce

1.  Test object (with attachment)
```
$ bw list items --search "Test Object"
? Master password: [hidden]
[{"object":"item","id":"e276050e-1c71-42ac-95eb-ad3300f63840","organizationId":null,"folderId":"0d62e546-ec44-4709-b6c6-ad3300f10e11","type":1,"name":"Test Object","notes":"test","favorite":false,"fields":[{"name":"test","value":"test","type":0},{"name":"test_hidden","value":"test","type":1},{"name":"test_boolean","value":"true","type":2}],"login":{"uris":[{"match":null,"uri":"https://test.example.com"}],"username":"test","password":"testtest","totp":"123456","passwordRevisionDate":null},"collectionIds":[],"attachments":[{"id":"blbnhj7zj17rzw2zy3xatxsi4d6n1xbg","fileName":"Test.txt","size":"65","sizeName":"65 Bytes","url":"https://host.example.com/attachments/e276050e-1c71-42ac-95eb-ad3300f63840/blbnhj7zj17rzw2zy3xatxsi4d6n1xbg"}],"revisionDate":"2021-05-25T14:56:27.513Z"}]
```

2. Try to get attachment (by id):
```
$ bw get attachment blbnhj7zj17rzw2zy3xatxsi4d6n1xbg --itemid e276050e-1c71-42ac-95eb-ad3300f63840
? Master password: [hidden]
(node:2885855) UnhandledPromiseRejectionWarning: Error
    at get_command_GetCommand.<anonymous> (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:27599:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:27338:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2885855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2885855) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

2. Try to get attachment (by name):
```
$ bw get attachment Test.txt --itemid e276050e-1c71-42ac-95eb-ad3300f63840
? Master password: [hidden]
(node:2885687) UnhandledPromiseRejectionWarning: Error
    at get_command_GetCommand.<anonymous> (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:27599:27)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:27338:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2885687) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2885687) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Expected Result

Retrieve attachment

## Actual Result

`UnhandledPromiseRejectionWarning: Error`

## Environment

- Operating system: CentOS 8.2.2004
- Shell: bash
- Build Version (run `bw --version`): 1.16.0

**Comment by ggiesen** [comment] 2021-08-28 20:36
Updating my server from 1.39.4 to 1.42.2 seems to have solved this issue.

**Comment by henriqueqc** [comment] 2021-08-30 18:56
Updating `bw` to version 1.18.0 fixed for me.

**Comment by eliykat** [comment] 2021-08-30 21:29
I'm glad you've been able to fix it in your cases, but this is something I'd like us to look at - we didn't intend to break backwards compatibility.

**Comment by eliykat** [comment] 2022-01-14 05:22
We haven't had any further reports about this and I was unable to reproduce it when I briefly tested it at the time. I'm going to close this issue again.

**Closed by eliykat** 2022-01-14 05:22 UTC
