### ISSUE TITLE
Pkg: FLAGS_MISMATCH error if environment variable NODE_OPTIONS is set

### ISSUE THREAD

**Issue by wttw** [bitwarden/cli#241] opened 2021-03-01 11:49 UTC
I have `NODE_OPTIONS` set to `--max_old_space_size=4096` on Linux using bw 1.14.0.

Running bw it just prints `Pkg: FLAGS_MISMATCH` around a thousand times and there's no other output.

This seems to be a known issue with pkg that can be mitigated temporarily by unsetting NODE_OPTIONS or more permanently with a packaging change, e.g. https://github.com/che-incubator/chectl/issues/74

**Comment by wttw** [comment] 2021-03-10 17:18
I don't quite understand pkg enough to say, but...

`NODE_OPTIONS= /usr/local/bin/bw` works correctly, printing the help text.

`NODE_OPTIONS=--foo /usr/local/bin/bw` errors out with "foo is not supported in NODE_OPTIONS"

`NODE_OPTIONS=--max_old_space_size=4096 /usr/local/bin/bw` or `NODE_OPTIONS=--abort-on-uncaught-exception /usr/local/bin/bw` print a thousand lines of Pkg: FLAGS_MISMATCH.

**Comment by MGibson1** [comment] 2021-03-10 17:53
How did you originally install bw? Maybe it's a discrepancy between install methods

**Comment by MGibson1** [comment] 2021-03-10 20:05
I was able to reproduce this -- sorry, apparently my brain wasn't working well. I was using a Node script, not a `pkg` compiled binary... duh. Thank you for your help.

Anyway, this seems to be a super old issue with `pkg`. I really want to call this an upstream issue because I don't think it's tenable as a consumer of the dependency to whack-a-mole every node and v8 option a user sets in our `package.json`. I commented on what appears to be the [original pkg issue](https://github.com/vercel/pkg/issues/484), but I'm not sure of the traction that issue will ever get...

**Comment by wttw** [comment] 2021-03-11 08:23
I mostly agree, though max_old_space_size is a particularly common one to have set globally as it's needed for webpack.

But anyone who's doing enough javascript work to need that can easily use the npm install of bw instead.

**Comment by MGibson1** [comment] 2021-03-11 14:51
I agree. I'm going to close this issue in light of that and get something on the help documentation to try and short circuit anyone else who has this issue.

The recommendation will be to check your environment for `NODE_OPTIONS` and/or install with npm. I'd hazard that anyone with `NODE_OPTIONS` explicitly set should have npm and node.

If you (or anyone else) disagrees or has a better solution, feel free to reopen and we can discuss.

**Closed by MGibson1** 2021-03-11 14:51 UTC
