### ISSUE TITLE
Syncing failed: Error

### ISSUE THREAD

**Issue by willpower232** [bitwarden/cli#234] opened 2021-02-21 17:17 UTC
I successfully migrated a lastpass account to bitwarden and syncing and export using the CLI worked flawlessly.

However now I have added a few more passwords manually, I am unable to sync or export. Export just fails with no error message (it did briefly say "mac failed" but I'm not sure if that was related to the vault being locked accidentally) however syncing tells me "error"

![image](https://user-images.githubusercontent.com/1619102/108632772-9038e280-7468-11eb-8897-faae114a849f.png)

I'm guessing from here that theres no more detail I can see where it is going wrong without compiling something manually and seeing what the exception is?

https://github.com/bitwarden/cli/blob/57f7cf607ae5ae5282c0d78a095c9bd3dba24582/src/commands/sync.command.ts#L22

**Comment by MGibson1** [comment] 2021-03-10 16:08
@willpower232. That is indeed a lame message. If you're willing/able I'd love if you could step through a debugger and see what threw.

Without that, my first guess would be colliding edits of items. Did you edit any existing items in CLI or somewhere else? I can also recommend contacting support. They may have seen this before and have more likely causes/solutions

**Comment by Crocmagnon** [comment] 2021-03-16 09:15
I'm also affected by this issue, here's the error I got:

```
$ bw sync
? Master password: [hidden]
/usr/local/Cellar/bitwarden-cli/1.15.0/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:25637
                return Response.error('Syncing failed: ' + e.toString());
                                                             ^

TypeError: Cannot read property 'toString' of null
    at sync_command_SyncCommand.<anonymous> (/usr/local/Cellar/bitwarden-cli/1.15.0/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:25637:62)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/Cellar/bitwarden-cli/1.15.0/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:25614:65)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by MGibson1** [comment] 2021-03-29 13:38
@Crocmagnon I have a similar question to you, though your error is more confusing.

Did you do some edits in CLI and some in some other client without syncing? Perhaps you have colliding items.

Can you or @willpower232 provide some recreation details?

**Comment by willpower232** [comment] 2021-03-29 17:12
I will try again in the next day or two, I'm not super familiar with debugging node, do you have any instructions/tips/steers on this?

**Comment by MGibson1** [comment] 2021-03-29 18:29
It's not terribly easy. The simplest way I've found is to use VSCode/code-oss and utilize it's debugger. We have a launch script checked into source control which can be updated to whatever command you want to debug.

**Comment by Crocmagnon** [comment] 2021-04-11 07:51
Unfortunately I can't reproduce the issue. It seems gone after logging out/logging in with the CLI.

**Comment by willpower232** [comment] 2021-04-18 18:55
Logging out and in cleared it and I haven't been able to reproduce either 😅 

I should have tried debugging first since I'd left it in a broken state 😞 

I did also update to the latest version (1.14 to 1.15.1) so maybe that helped it not happen again(?)

Wildly off topic, I had a Bad Time ™️ since my passwords contained all sorts of special characters which thoroughly upset bash scripting but I eventually stumbled upon a different way of passing them to jq with `--arg`

```sh
newitem=$(bw get template item | jq ".name=\"$item\" | .login=$(bw get template item.login | jq --arg username $username --arg password $password '.username=$username | .password=$password')" | bw encode | bw create item)
```

So it may be useful to some if this was documented properly to avoid future heartache.

That said, it seems I cannot get 100% of my passwords into bash script in spite of the above since several seem to have just too many awkward symbols so I'll be resetting passwords for a while 😬

**Comment by MGibson1** [comment] 2021-04-19 13:17
No worries, at least we have some remediation if this comes up more.

Thanks for the tip! @fschillingeriv what do you think about some scripting hints in CLI documentation?

**Comment by ThomasFike** [comment] 2021-12-29 19:52
I also ran into this issue today but when trying to do an edit on an item. It was continually print failed mac multiple times which caused a failure because the password entry would read failed mac instead of the password causing issues. I logged out and back in as suggested and now have no issues.
`bw get item <id-redacted> | jq '.login.uris[0].uri="https://newurl.com"' | bw encode |
bw edit item <id-redacted> --response` 

> `mac failed.`
> `mac failed.`
> `? Master password: [input is hidden] mac failed.`
> `mac failed.`
> `? Master password: [hidden]`
> `? Master password: [hidden]`
> `{"success":false,"message":"Invalid master password."}`

**Comment by eliykat** [comment] 2022-02-02 01:21
@ThomasFike FYI only: The 'mac failed' message indicates that there was some error in decrypting an item. At a guess, maybe corrupted local data, or a change of master password or an encryption key rotation since you last logged in with this client. Logging out and back in would fix any of these issues. Glad you got it resolved.

The original report here seems to be resolved, so I'm closing this issue.

**Closed by eliykat** 2022-02-02 01:21 UTC
